#### 34. Create an array , np.arange(12).reshape(3,4). Replace the array elements with their square values if the element is an even number. Keep the odd numbers as such. Display the resulting array.

In [14]:
# Using numpy a python library for arrays as it is faster in calculation than lists

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [16]:
#importing numpy package and giving np as alias

In [18]:
import numpy as np


In [26]:
# Creating an array  np.arange(12).reshape(3,4)

In [20]:
np.arange(12).reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
array_greeshma=np.arange(12).reshape(3,4)

In [24]:
print(array_greeshma)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [28]:
# Replace the array elements with their square values if the element is an even number. Keep the odd numbers as such.

In [32]:
array_greeshma[1][0]

4

In [34]:
array_greeshma[0][0]

0

In [36]:
# Logic: if condition(arr[0][0]%2==0) then np.square else arr[0][0]

In [38]:
# https://stackoverflow.com/questions/42540224/conditional-operations-on-numpy-arrays

In [44]:
# Since numpy is used to perform on entire array s we cannot use if else condition 

In [42]:
# using np.where() ---> np.where(condition; if true what to do, if false what to do)

In [46]:
np.where(array_greeshma%2==0, np.square(array_greeshma), array_greeshma)

array([[  0,   1,   4,   3],
       [ 16,   5,  36,   7],
       [ 64,   9, 100,  11]])

In [48]:
resulting_array=np.where(array_greeshma%2==0, np.square(array_greeshma), array_greeshma)

In [50]:
print(resulting_array)

[[  0   1   4   3]
 [ 16   5  36   7]
 [ 64   9 100  11]]
